### PR TITLE
fix(event): Event stack trace fixes

### PR DESCRIPTION
**Pull request by Shubhdeep12**
Before opening this PR:

- [x] I added a [Changeset Entry](https://spotlightjs.com/contribute/changesets/) with `pnpm changeset:add`
- [x] I referenced issues that this PR addresses

1. Made filename as optional in EventFrame
2. Added module name as a fallback when the filename is not present in Event Stack Trace.
3. Module name is preferred in case the platform is Java.

#331 

image

### CODE REVIEW

**Review by Lms24 — APPROVED** [review]
thanks!

**Comment by Lms24** [comment]
In case we get some fixtures for Java events, let's make sure to add tests for them.

**Comment by Shubhdeep12** [comment]
> In case we get some fixtures for Java events, let's make sure to add tests for them. Feel free to tackle this in a follow-up PR.

definitely.

**Review by Lms24 — APPROVED** [review]
thx!

**Pull request merged**
