### PR TITLE
fix(tabs): Default active detail tab in Events

### PR DESCRIPTION
**Pull request by Shubhdeep12**
Currently in EventDetails 
Default active tab is Details
But we are only utilizing react-router active nodes, due to which Details tab is not shown in active state.

Added condition to check both active node OR active boolean

### CODE REVIEW

**Review by Lms24 — CHANGES_REQUESTED** [review]
I think manually keeping track of an active tab was a leftover from refactoring spotlight to an integration based architecture. Let's not use locally kept active state but always use the router's active node.

**Comment by dcramer** [comment]
Coincidentally just was mentioning this in Slack ;)

We def need to refactor these to use router and I broke this when I was making other changes

**Comment by Shubhdeep12** [comment]
Hi @dcramer @Lms24 
just pushed a fix that will use react router active node only.

**Comment by HazAT** [comment]
Thx

**Pull request merged**
