### PR TITLE
Vite Integration docs for spotlight/sidecar fix.

### PR DESCRIPTION
**Pull request by theetherGit**
Before opening this PR:
* [ ] I added a [Changeset Entry](https://spotlightjs.com/contribute/changesets/) with `pnpm changeset:add`
* [ ] I referenced issues that this PR addresses

Vite Integration docs for spotlight/sidecar fix.

### CODE REVIEW

**Review by Shubhdeep12 — APPROVED** [review]
thanks

**Review by Lms24 — COMMENTED** [review]
Hmm it's been a while since I worked on this but IIRC, the `@spotlightjs/spotlight` package should also be able to run the sidecar. Is there a particular reason, adding the `@spotlightjs/sidecar` package makes more sense?

**Review by Lms24 — CHANGES_REQUESTED** [review]
Just gonna request changes so we don't accidentally merge this before we clarify the intent

**Comment by Shubhdeep12** [comment]
Yes @Lms24 
running npx @spotlightjs/spotlight will run the sidecar. 

 But looks like its one of the way to run sidecar for vite powered apps. And for them it is needed to import this package. 
And this was a typo error which was fixed in this PR

**Review by Lms24 — APPROVED** [review]
Oh yeah that makes sense, thx for explaining!

**Pull request merged**
